[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

# Additional configurations
remappings = [
    'forge-std=lib/forge-std/src/',
]

[rpc_endpoints]
mainnet = "${RPC_URL_MAINNET}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }